/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskDetail: typeof import('./src/components/TaskDetail.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    TodoListLayout: typeof import('./src/components/Layouts/TodoListLayout.vue')['default']
    TodoListSidebar: typeof import('./src/components/TodoListSidebar.vue')['default']
  }
}
